### ISSUE TITLE
No System Tray Icon

### ISSUE THREAD

**Issue by awponder** [riyasy/RainProject#4]
After running the latest release to try to get snow, I now have no way to configure. There is no icon in taskbar or system tray area. 
![No Icon](https://github.com/user-attachments/assets/510f627e-502b-489a-9812-6825389939f9)

**Comment by riyasy** [comment]
I have the tray icon coming my windows 11 machine. I shall check in Windows 10 after setting up one.
1) Where you able to see the tray icon in previous releases ?
2) Can you check taskbar settings and check if this is available in list of tray icons to be displayed?

If nothing works at the moment, to just see the snow
Open "C:\Users\<USER NAME>\AppData\Roaming\let-it-rain.ini" and set ParticleType to 1.

[Settings]
MaxParticles=50
WindSpeed=3
ParticleColor=00AAAAAA
**ParticleType=1**

**Comment by awponder** [comment]
That works for the snow to work. Thank you!

**Comment by riyasy** [comment]
I have created a fix for Windows 10. I shall release tomorrow.

**Comment by riyasy** [comment]
published fix.

**Comment by awponder** [comment]
Works great! Thank you.
